name: rh20t_rlds
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - absl-py==2.4.0
      - annotated-doc==0.0.4
      - anyio==4.14.1
      - astunparse==1.6.3
      - attrs==26.1.0
      - av==17.1.0
      - beautifulsoup4==4.15.0
      - certifi==2026.6.17
      - charset-normalizer==3.4.7
      - click==8.4.2
      - colorama==0.4.6
      - dm-tree==0.1.10
      - docstring-parser==0.18.0
      - einops==0.8.2
      - etils==1.14.0
      - filelock==3.29.4
      - flatbuffers==25.12.19
      - fsspec==2026.6.0
      - gast==0.7.0
      - gdown==6.1.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.75.0
      - grpcio==1.81.1
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.5.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.21.0
      - idna==3.18
      - immutabledict==4.3.1
      - importlib-resources==7.1.0
      - keras==3.15.0
      - libclang==18.1.1
      - markdown-it-py==4.2.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - namex==0.1.0
      - numpy==2.4.6
      - opencv-python==4.13.0.92
      - opt-einsum==3.4.0
      - optree==0.19.1
      - pandas==3.0.3
      - promise==2.3
      - protobuf==7.35.1
      - psutil==7.2.2
      - pyarrow==24.0.0
      - pygments==2.20.0
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - requests==2.34.2
      - rich==15.0.0
      - shellingham==1.5.4
      - simple-parsing==0.1.8
      - six==1.17.0
      - soupsieve==2.8.4
      - tensorflow==2.21.0
      - tensorflow-datasets==4.9.10
      - tensorflow-metadata==1.21.0
      - termcolor==3.3.0
      - toml==0.10.2
      - tqdm==4.68.3
      - transforms3d==0.4.2
      - typer==0.25.1
      - typing-extensions==4.15.0
      - tzdata==2026.2
      - urllib3==2.7.0
      - wrapt==2.2.2
      - zipp==4.1.0
